server:
  port: 8020

spring:
  application:
    name: smp
  profiles:
    active: prod
  devtools:
    livereload:
      enabled: true
  http:
    encoding:
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    host: 192.168.1.106
    port: 5672
    username: admin
    password: admin
    #开启消息确认模式
    publisher-returns: true
    publisher-confirms: true
    template:
      #开启mandatory: true, basic.return方法将消息返还给生产者
      mandatory: true
    listener:
      #      direct:
      #        acknowledge-mode: manual
      simple:
        #手动ACK
        acknowledge-mode: manual
        #        concurrency: 1
        #        max-concurrency: 1
        #        prefetch: 1
        retry:
          enabled: true

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: org.sc.smp.**.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    cache-enabled: true
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1

swagger:
  base-package: org.sc
  exclude-path: /aa/**

logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN